// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// ApplicationCacheApplicationCacheStatusUpdated ...
type ApplicationCacheApplicationCacheStatusUpdated struct {
	// FrameID Identifier of the frame containing document whose application cache updated status.
	FrameID *PageFrameID `json:"frameId"`

	// ManifestURL Manifest URL.
	ManifestURL string `json:"manifestURL"`

	// Status Updated application cache status.
	Status int64 `json:"status"`
}

// MethodName interface
func (evt ApplicationCacheApplicationCacheStatusUpdated) MethodName() string {
	return "ApplicationCache.applicationCacheStatusUpdated"
}

// Load json
func (evt ApplicationCacheApplicationCacheStatusUpdated) Load(b []byte) *ApplicationCacheApplicationCacheStatusUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}

// ApplicationCacheNetworkStateUpdated ...
type ApplicationCacheNetworkStateUpdated struct {
	// IsNowOnline ...
	IsNowOnline bool `json:"isNowOnline"`
}

// MethodName interface
func (evt ApplicationCacheNetworkStateUpdated) MethodName() string {
	return "ApplicationCache.networkStateUpdated"
}

// Load json
func (evt ApplicationCacheNetworkStateUpdated) Load(b []byte) *ApplicationCacheNetworkStateUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}
