// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// CastSinksUpdated This is fired whenever the list of available sinks changes. A sink is a
// device or a software surface that you can cast to.
type CastSinksUpdated struct {
	// Sinks ...
	Sinks []*CastSink `json:"sinks"`
}

// MethodName interface
func (evt CastSinksUpdated) MethodName() string {
	return "Cast.sinksUpdated"
}

// Load json
func (evt CastSinksUpdated) Load(b []byte) *CastSinksUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}

// CastIssueUpdated This is fired whenever the outstanding issue/error message changes.
// |issueMessage| is empty if there is no issue.
type CastIssueUpdated struct {
	// IssueMessage ...
	IssueMessage string `json:"issueMessage"`
}

// MethodName interface
func (evt CastIssueUpdated) MethodName() string {
	return "Cast.issueUpdated"
}

// Load json
func (evt CastIssueUpdated) Load(b []byte) *CastIssueUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}
