// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// ConsoleMessageAdded Issued when new console message is added.
type ConsoleMessageAdded struct {
	// Message Console message that has been added.
	Message *ConsoleConsoleMessage `json:"message"`
}

// MethodName interface
func (evt ConsoleMessageAdded) MethodName() string {
	return "Console.messageAdded"
}

// Load json
func (evt ConsoleMessageAdded) Load(b []byte) *ConsoleMessageAdded {
	E(json.Unmarshal(b, &evt))
	return &evt
}
