// This file is generated by "./lib/proto/cmd/gen"

package proto

// DOMDebuggerDOMBreakpointType DOM breakpoint type.
type DOMDebuggerDOMBreakpointType string

const (
	// DOMDebuggerDOMBreakpointTypeSubtreeModified enum value
	DOMDebuggerDOMBreakpointTypeSubtreeModified DOMDebuggerDOMBreakpointType = "subtree-modified"

	// DOMDebuggerDOMBreakpointTypeAttributeModified enum value
	DOMDebuggerDOMBreakpointTypeAttributeModified DOMDebuggerDOMBreakpointType = "attribute-modified"

	// DOMDebuggerDOMBreakpointTypeNodeRemoved enum value
	DOMDebuggerDOMBreakpointTypeNodeRemoved DOMDebuggerDOMBreakpointType = "node-removed"
)

// DOMDebuggerEventListener Object event listener.
type DOMDebuggerEventListener struct {
	// Type `EventListener`'s type.
	Type string `json:"type"`

	// UseCapture `EventListener`'s useCapture.
	UseCapture bool `json:"useCapture"`

	// Passive `EventListener`'s passive flag.
	Passive bool `json:"passive"`

	// Once `EventListener`'s once flag.
	Once bool `json:"once"`

	// ScriptID Script id of the handler code.
	ScriptID *RuntimeScriptID `json:"scriptId"`

	// LineNumber Line number in the script (0-based).
	LineNumber int64 `json:"lineNumber"`

	// ColumnNumber Column number in the script (0-based).
	ColumnNumber int64 `json:"columnNumber"`

	// Handler Event handler function value.
	Handler *RuntimeRemoteObject `json:"handler,omitempty"`

	// OriginalHandler Event original handler function value.
	OriginalHandler *RuntimeRemoteObject `json:"originalHandler,omitempty"`

	// BackendNodeID Node the listener is added to (if any).
	BackendNodeID *DOMBackendNodeID `json:"backendNodeId,omitempty"`
}
