// This file is generated by "./lib/proto/cmd/gen"

package proto

// DOMStorageStorageID DOM Storage identifier.
type DOMStorageStorageID struct {
	// SecurityOrigin Security origin for the storage.
	SecurityOrigin string `json:"securityOrigin"`

	// IsLocalStorage Whether the storage is local storage (not session storage).
	IsLocalStorage bool `json:"isLocalStorage"`
}

// DOMStorageItem DOM Storage item.
type DOMStorageItem []string
