// This file is generated by "./lib/proto/cmd/gen"

package proto

// FetchRequestID Unique request identifier.
type FetchRequestID string

// FetchRequestStage (experimental) Stages of the request to handle. Request will intercept before the request is
// sent. Response will intercept after the response is received (but before response
// body is received.
type FetchRequestStage string

const (
	// FetchRequestStageRequest enum value
	FetchRequestStageRequest FetchRequestStage = "Request"

	// FetchRequestStageResponse enum value
	FetchRequestStageResponse FetchRequestStage = "Response"
)

// FetchRequestPattern (experimental) ...
type FetchRequestPattern struct {
	// URLPattern Wildcards ('*' -> zero or more, '?' -> exactly one) are allowed. Escape character is
	// backslash. Omitting is equivalent to "*".
	URLPattern string `json:"urlPattern,omitempty"`

	// ResourceType If set, only requests for matching resource types will be intercepted.
	ResourceType *NetworkResourceType `json:"resourceType,omitempty"`

	// RequestStage Stage at wich to begin intercepting requests. Default is Request.
	RequestStage *FetchRequestStage `json:"requestStage,omitempty"`
}

// FetchHeaderEntry Response HTTP header entry
type FetchHeaderEntry struct {
	// Name ...
	Name string `json:"name"`

	// Value ...
	Value string `json:"value"`
}

// FetchAuthChallenge (experimental) Authorization challenge for HTTP status code 401 or 407.
type FetchAuthChallenge struct {
	// Source Source of the authentication challenge.
	Source string `json:"source,omitempty"`

	// Origin Origin of the challenger.
	Origin string `json:"origin"`

	// Scheme The authentication scheme used, such as basic or digest
	Scheme string `json:"scheme"`

	// Realm The realm of the challenge. May be empty.
	Realm string `json:"realm"`
}

// FetchAuthChallengeResponse (experimental) Response to an AuthChallenge.
type FetchAuthChallengeResponse struct {
	// Response The decision on what to do in response to the authorization challenge.  Default means
	// deferring to the default behavior of the net stack, which will likely either the Cancel
	// authentication or display a popup dialog box.
	Response string `json:"response"`

	// Username The username to provide, possibly empty. Should only be set if response is
	// ProvideCredentials.
	Username string `json:"username,omitempty"`

	// Password The password to provide, possibly empty. Should only be set if response is
	// ProvideCredentials.
	Password string `json:"password,omitempty"`
}
