// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// HeadlessExperimentalNeedsBeginFramesChanged (deprecated) Issued when the target starts or stops needing BeginFrames.
// Deprecated. Issue beginFrame unconditionally instead and use result from
// beginFrame to detect whether the frames were suppressed.
type HeadlessExperimentalNeedsBeginFramesChanged struct {
	// NeedsBeginFrames True if BeginFrames are needed, false otherwise.
	NeedsBeginFrames bool `json:"needsBeginFrames"`
}

// MethodName interface
func (evt HeadlessExperimentalNeedsBeginFramesChanged) MethodName() string {
	return "HeadlessExperimental.needsBeginFramesChanged"
}

// Load json
func (evt HeadlessExperimentalNeedsBeginFramesChanged) Load(b []byte) *HeadlessExperimentalNeedsBeginFramesChanged {
	E(json.Unmarshal(b, &evt))
	return &evt
}
