// This file is generated by "./lib/proto/cmd/gen"

package proto

// HeapProfilerHeapSnapshotObjectID Heap snapshot object id.
type HeapProfilerHeapSnapshotObjectID string

// HeapProfilerSamplingHeapProfileNode Sampling Heap Profile node. Holds callsite information, allocation statistics and child nodes.
type HeapProfilerSamplingHeapProfileNode struct {
	// CallFrame Function location.
	CallFrame *RuntimeCallFrame `json:"callFrame"`

	// SelfSize Allocations size in bytes for the node excluding children.
	SelfSize float64 `json:"selfSize"`

	// ID Node id. Ids are unique across all profiles collected between startSampling and stopSampling.
	ID int64 `json:"id"`

	// Children Child nodes.
	Children []*HeapProfilerSamplingHeapProfileNode `json:"children"`
}

// HeapProfilerSamplingHeapProfileSample A single sample from a sampling profile.
type HeapProfilerSamplingHeapProfileSample struct {
	// Size Allocation size in bytes attributed to the sample.
	Size float64 `json:"size"`

	// NodeID Id of the corresponding profile tree node.
	NodeID int64 `json:"nodeId"`

	// Ordinal Time-ordered sample ordinal number. It is unique across all profiles retrieved
	// between startSampling and stopSampling.
	Ordinal float64 `json:"ordinal"`
}

// HeapProfilerSamplingHeapProfile Sampling profile.
type HeapProfilerSamplingHeapProfile struct {
	// Head ...
	Head *HeapProfilerSamplingHeapProfileNode `json:"head"`

	// Samples ...
	Samples []*HeapProfilerSamplingHeapProfileSample `json:"samples"`
}
