// This file is generated by "./lib/proto/cmd/gen"

package proto

import (
	"encoding/json"
)

// InspectorDisable Disables inspector domain notifications.
type InspectorDisable struct {
}

// InspectorDisableResult type
type InspectorDisableResult struct {
}

// Call of the command, sessionID is optional.
func (m InspectorDisable) Call(c *Call) (*InspectorDisableResult, error) {
	bin, err := c.Client.Call(c.Context, c.SessionID, "InspectorDisable", m)
	if err != nil {
		return nil, err
	}

	var res InspectorDisableResult
	err = json.Unmarshal(bin, &res)
	if err != nil {
		return nil, err
	}

	return &res, nil
}

// InspectorEnable Enables inspector domain notifications.
type InspectorEnable struct {
}

// InspectorEnableResult type
type InspectorEnableResult struct {
}

// Call of the command, sessionID is optional.
func (m InspectorEnable) Call(c *Call) (*InspectorEnableResult, error) {
	bin, err := c.Client.Call(c.Context, c.SessionID, "InspectorEnable", m)
	if err != nil {
		return nil, err
	}

	var res InspectorEnableResult
	err = json.Unmarshal(bin, &res)
	if err != nil {
		return nil, err
	}

	return &res, nil
}
