// This file is generated by "./lib/proto/cmd/gen"

package proto

// IOStreamHandle This is either obtained from another method or specifed as `blob:&lt;uuid&gt;` where
// `&lt;uuid&gt` is an UUID of a Blob.
type IOStreamHandle string
