// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// LogEntryAdded Issued when new message was logged.
type LogEntryAdded struct {
	// Entry The entry.
	Entry *LogLogEntry `json:"entry"`
}

// MethodName interface
func (evt LogEntryAdded) MethodName() string {
	return "Log.entryAdded"
}

// Load json
func (evt LogEntryAdded) Load(b []byte) *LogEntryAdded {
	E(json.Unmarshal(b, &evt))
	return &evt
}
