// This file is generated by "./lib/proto/cmd/gen"

package proto

// LogLogEntry Log entry.
type LogLogEntry struct {
	// Source Log entry source.
	Source string `json:"source"`

	// Level Log entry severity.
	Level string `json:"level"`

	// Text Logged text.
	Text string `json:"text"`

	// Timestamp Timestamp when this entry was added.
	Timestamp *RuntimeTimestamp `json:"timestamp"`

	// URL URL of the resource if known.
	URL string `json:"url,omitempty"`

	// LineNumber Line number in the resource.
	LineNumber int64 `json:"lineNumber,omitempty"`

	// StackTrace JavaScript stack trace.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`

	// NetworkRequestID Identifier of the network request associated with this entry.
	NetworkRequestID *NetworkRequestID `json:"networkRequestId,omitempty"`

	// WorkerID Identifier of the worker associated with this entry.
	WorkerID string `json:"workerId,omitempty"`

	// Args Call arguments.
	Args []*RuntimeRemoteObject `json:"args,omitempty"`
}

// LogViolationSetting Violation configuration setting.
type LogViolationSetting struct {
	// Name Violation type.
	Name string `json:"name"`

	// Threshold Time threshold to trigger upon.
	Threshold float64 `json:"threshold"`
}
