// This file is generated by "./lib/proto/cmd/gen"

package proto

// OverlayHighlightConfig Configuration data for the highlighting of page elements.
type OverlayHighlightConfig struct {
	// ShowInfo Whether the node info tooltip should be shown (default: false).
	ShowInfo bool `json:"showInfo,omitempty"`

	// ShowStyles Whether the node styles in the tooltip (default: false).
	ShowStyles bool `json:"showStyles,omitempty"`

	// ShowRulers Whether the rulers should be shown (default: false).
	ShowRulers bool `json:"showRulers,omitempty"`

	// ShowExtensionLines Whether the extension lines from node to the rulers should be shown (default: false).
	ShowExtensionLines bool `json:"showExtensionLines,omitempty"`

	// ContentColor The content box highlight fill color (default: transparent).
	ContentColor *DOMRGBA `json:"contentColor,omitempty"`

	// PaddingColor The padding highlight fill color (default: transparent).
	PaddingColor *DOMRGBA `json:"paddingColor,omitempty"`

	// BorderColor The border highlight fill color (default: transparent).
	BorderColor *DOMRGBA `json:"borderColor,omitempty"`

	// MarginColor The margin highlight fill color (default: transparent).
	MarginColor *DOMRGBA `json:"marginColor,omitempty"`

	// EventTargetColor The event target element highlight fill color (default: transparent).
	EventTargetColor *DOMRGBA `json:"eventTargetColor,omitempty"`

	// ShapeColor The shape outside fill color (default: transparent).
	ShapeColor *DOMRGBA `json:"shapeColor,omitempty"`

	// ShapeMarginColor The shape margin fill color (default: transparent).
	ShapeMarginColor *DOMRGBA `json:"shapeMarginColor,omitempty"`

	// CSSGridColor The grid layout color (default: transparent).
	CSSGridColor *DOMRGBA `json:"cssGridColor,omitempty"`
}

// OverlayInspectMode ...
type OverlayInspectMode string

const (
	// OverlayInspectModeSearchForNode enum value
	OverlayInspectModeSearchForNode OverlayInspectMode = "searchForNode"

	// OverlayInspectModeSearchForUAShadowDOM enum value
	OverlayInspectModeSearchForUAShadowDOM OverlayInspectMode = "searchForUAShadowDOM"

	// OverlayInspectModeCaptureAreaScreenshot enum value
	OverlayInspectModeCaptureAreaScreenshot OverlayInspectMode = "captureAreaScreenshot"

	// OverlayInspectModeShowDistances enum value
	OverlayInspectModeShowDistances OverlayInspectMode = "showDistances"

	// OverlayInspectModeNone enum value
	OverlayInspectModeNone OverlayInspectMode = "none"
)
