// This file is generated by "./lib/proto/cmd/gen"

package proto

// PerformanceMetric Run-time execution metric.
type PerformanceMetric struct {
	// Name Metric name.
	Name string `json:"name"`

	// Value Metric value.
	Value float64 `json:"value"`
}
