// This file is generated by "./lib/proto/cmd/gen"

package proto

import (
	"encoding/json"
)

// SchemaGetDomains Returns supported domains.
type SchemaGetDomains struct {
}

// SchemaGetDomainsResult type
type SchemaGetDomainsResult struct {
	// Domains List of supported domains.
	Domains []*SchemaDomain `json:"domains"`
}

// Call of the command, sessionID is optional.
func (m SchemaGetDomains) Call(c *Call) (*SchemaGetDomainsResult, error) {
	bin, err := c.Client.Call(c.Context, c.SessionID, "SchemaGetDomains", m)
	if err != nil {
		return nil, err
	}

	var res SchemaGetDomainsResult
	err = json.Unmarshal(bin, &res)
	if err != nil {
		return nil, err
	}

	return &res, nil
}
