// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// StorageCacheStorageContentUpdated A cache's contents have been modified.
type StorageCacheStorageContentUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`

	// CacheName Name of cache in origin.
	CacheName string `json:"cacheName"`
}

// MethodName interface
func (evt StorageCacheStorageContentUpdated) MethodName() string {
	return "Storage.cacheStorageContentUpdated"
}

// Load json
func (evt StorageCacheStorageContentUpdated) Load(b []byte) *StorageCacheStorageContentUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}

// StorageCacheStorageListUpdated A cache has been added/deleted.
type StorageCacheStorageListUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
}

// MethodName interface
func (evt StorageCacheStorageListUpdated) MethodName() string {
	return "Storage.cacheStorageListUpdated"
}

// Load json
func (evt StorageCacheStorageListUpdated) Load(b []byte) *StorageCacheStorageListUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}

// StorageIndexedDBContentUpdated The origin's IndexedDB object store has been modified.
type StorageIndexedDBContentUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`

	// DatabaseName Database to update.
	DatabaseName string `json:"databaseName"`

	// ObjectStoreName ObjectStore to update.
	ObjectStoreName string `json:"objectStoreName"`
}

// MethodName interface
func (evt StorageIndexedDBContentUpdated) MethodName() string {
	return "Storage.indexedDBContentUpdated"
}

// Load json
func (evt StorageIndexedDBContentUpdated) Load(b []byte) *StorageIndexedDBContentUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}

// StorageIndexedDBListUpdated The origin's IndexedDB database list has been modified.
type StorageIndexedDBListUpdated struct {
	// Origin Origin to update.
	Origin string `json:"origin"`
}

// MethodName interface
func (evt StorageIndexedDBListUpdated) MethodName() string {
	return "Storage.indexedDBListUpdated"
}

// Load json
func (evt StorageIndexedDBListUpdated) Load(b []byte) *StorageIndexedDBListUpdated {
	E(json.Unmarshal(b, &evt))
	return &evt
}
