// This file is generated by "./lib/proto/cmd/gen"

package proto

import "encoding/json"

// TetheringAccepted Informs that port was successfully bound and got a specified connection id.
type TetheringAccepted struct {
	// Port Port number that was successfully bound.
	Port int64 `json:"port"`

	// ConnectionID Connection id to be used.
	ConnectionID string `json:"connectionId"`
}

// MethodName interface
func (evt TetheringAccepted) MethodName() string {
	return "Tethering.accepted"
}

// Load json
func (evt TetheringAccepted) Load(b []byte) *TetheringAccepted {
	E(json.Unmarshal(b, &evt))
	return &evt
}
