// This file is generated by "./lib/proto/cmd/gen"

package proto

import (
	"encoding/json"
)

// TetheringBind Request browser port binding.
type TetheringBind struct {
	// Port Port number to bind.
	Port int64 `json:"port"`
}

// TetheringBindResult type
type TetheringBindResult struct {
}

// Call of the command, sessionID is optional.
func (m TetheringBind) Call(c *Call) (*TetheringBindResult, error) {
	bin, err := c.Client.Call(c.Context, c.SessionID, "TetheringBind", m)
	if err != nil {
		return nil, err
	}

	var res TetheringBindResult
	err = json.Unmarshal(bin, &res)
	if err != nil {
		return nil, err
	}

	return &res, nil
}

// TetheringUnbind Request browser port unbinding.
type TetheringUnbind struct {
	// Port Port number to unbind.
	Port int64 `json:"port"`
}

// TetheringUnbindResult type
type TetheringUnbindResult struct {
}

// Call of the command, sessionID is optional.
func (m TetheringUnbind) Call(c *Call) (*TetheringUnbindResult, error) {
	bin, err := c.Client.Call(c.Context, c.SessionID, "TetheringUnbind", m)
	if err != nil {
		return nil, err
	}

	var res TetheringUnbindResult
	err = json.Unmarshal(bin, &res)
	if err != nil {
		return nil, err
	}

	return &res, nil
}
